service: cncb-resubmitting-faults-simulator

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - kinesis:PutRecord
        - kinesis:PutRecords
      Resource: ${cf:cncb-event-stream-${opt:stage}.streamArn}
  environment:
    STREAM_NAME: ${cf:cncb-event-stream-${opt:stage}.streamName}

functions:
  listener:
    handler: handler.listener
    events:
      - stream:
          type: kinesis
          arn: ${cf:cncb-event-stream-${opt:stage}.streamArn}
          batchSize: 100
          startingPosition: LATEST # TRIM_HORIZON
  simulate:
    handler: handler.simulate
