CloudWatchLoggingOptions: 
  Enabled: true
  LogGroupName:
    Ref: LogGroup
  LogStreamName:
    Ref: LogStream

ProcessingConfiguration:
  Enabled: true
  Processors: 
    - Parameters: 
      - ParameterName: LambdaArn
        ParameterValue:
          Fn::GetAtt: [ TransformerLambdaFunction, Arn ]
      Type: Lambda 

LogGroup: 
  Type: AWS::Logs::LogGroup

LogStream: 
  Type: AWS::Logs::LogStream
  Properties: 
    LogGroupName:
      Ref: LogGroup
    LogStreamName: datalake

KinesisRole:
  Type: AWS::IAM::Role
  Properties:
    AssumeRolePolicyDocument:
      Statement:
        - Effect: Allow
          Principal:
            Service: firehose.amazonaws.com
          Action: sts:AssumeRole
    Policies:               
      - PolicyName: consume
        PolicyDocument:
          Statement:
            - Effect: Allow
              Action:
                - kinesis:GetRecords
                - kinesis:GetShardIterator
                - kinesis:DescribeStream
                - kinesis:ListStreams
              Resource: ${cf:cncb-event-stream-${opt:stage}.streamArn}

DeliveryRole:
  Type: AWS::IAM::Role
  Properties:
    AssumeRolePolicyDocument:
      Statement:
        - Effect: Allow
          Principal:
            Service: firehose.amazonaws.com
          Action: sts:AssumeRole
    Policies:               
      - PolicyName: delivery
        PolicyDocument:
          Statement:
            - Effect: Allow
              Action:
                - s3:AbortMultipartUpload
                - s3:GetBucketLocation
                - s3:GetObject
                - s3:ListBucket
                - s3:ListBucketMultipartUploads
                - s3:PutObject
              Resource:
                - Fn::GetAtt: [ Bucket, Arn ]
                - Fn::Join:
                    - /
                    - - Fn::GetAtt: [ Bucket, Arn ]
                      - '*'
            - Effect: Allow
              Action:
                - logs:PutLogEvents
              Resource:
                - Fn::GetAtt: [ LogGroup, Arn ]
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
                - lambda:GetFunctionConfiguration
              Resource:
                - Fn::GetAtt: [ TransformerLambdaFunction, Arn ]

