service: cncb-data-lake-s3

provider:
  name: aws
  runtime: nodejs8.10

functions:
  transformer:
    handler: handler.transform
    timeout: 120

resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
    DeliveryStream:
      Type: AWS::KinesisFirehose::DeliveryStream
      Properties:
        DeliveryStreamType: KinesisStreamAsSource      
        KinesisStreamSourceConfiguration: 
          KinesisStreamARN: ${cf:cncb-event-stream-${opt:stage}.streamArn}
          RoleARN:
            Fn::GetAtt: [ KinesisRole, Arn ]
        ExtendedS3DestinationConfiguration:
          BucketARN:
            Fn::GetAtt: [ Bucket, Arn ]
          Prefix: ${cf:cncb-event-stream-${opt:stage}.streamName}/
          BufferingHints:
            IntervalInSeconds: 60
            SizeInMBs: 50
          CompressionFormat: UNCOMPRESSED
          RoleARN:
            Fn::GetAtt: [ DeliveryRole, Arn ]
          CloudWatchLoggingOptions: ${file(includes.yml):CloudWatchLoggingOptions}
          ProcessingConfiguration: ${file(includes.yml):ProcessingConfiguration}
    LogGroup: ${file(includes.yml):LogGroup}
    LogStream: ${file(includes.yml):LogStream}
    KinesisRole: ${file(includes.yml):KinesisRole}
    DeliveryRole: ${file(includes.yml):DeliveryRole}

  Outputs:
    DataLakeBucketName:
      Value:
        Ref: Bucket
