service: cncb-tuning-faas

plugins:
  - serverless-webpack

provider:
  name: aws
  # cfnRole: arn:aws:iam::${self:custom.accounts.${opt:acct}.accountNumber}:role/${opt:stage}-cfnRole
  runtime: nodejs8.10
  endpointType: REGIONAL
  memorySize: 1024
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        - Fn::GetAtt:
            - Table
            - Arn
  environment:
    TABLE_NAME: ${opt:stage}-${self:service}-things

custom:
  webpack:
    includeModules: true
package:
  individually: true

functions:
  save:
    handler: src/save/index.handle
    memorySize: 512
    events:
      - http:
          path: things
          method: post
          cors: true
  get:
    handler: src/get/index.handle
    events:
      - http:
          path: things/{id}
          method: get
          cors: true

resources:
  Resources:
    Table:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
